version: "3.8"
services:
  api:
    build:
      context: ../backend
      dockerfile: ../ops/backend/Dockerfile
    env_file:
      - ./env.backend
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:8080/health"]
      interval: 15s
      timeout: 5s
      retries: 10
    ports:
      - "8080:8080"
    working_dir: /app
    depends_on:
      postgres:
        condition: service_healthy

  cashier:
    build:
      context: ../frontend-cashier
      dockerfile: ../ops/frontend-cashier/Dockerfile
      args:
        API_REWRITE_TARGET: http://api:8080
    env_file:
      - ./env.frontend-cashier
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:3000"]
      interval: 20s
      timeout: 5s
      retries: 10
    ports:
      - "3000:3000"
    depends_on:
      api:
        condition: service_healthy

  dashboard:
    build:
      context: ../frontend-dashboard
      dockerfile: ../ops/frontend-dashboard/Dockerfile
      args:
        API_REWRITE_TARGET: http://api:8080
    env_file:
      - ./env.frontend-dashboard
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:3000"]
      interval: 20s
      timeout: 5s
      retries: 10
    ports:
      - "3001:3000"
    depends_on:
      api:
        condition: service_healthy

  postgres:
    image: postgres:16
    container_name: ktp-postgres
    environment:
      POSTGRES_USER: ktp
      POSTGRES_PASSWORD: ktp_pwd
      POSTGRES_DB: ktp_db
    ports:
      - "5432:5432"
    volumes:
      - ktp_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ktp -d ktp_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: ktp-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

networks:
  default:
    name: kuyumculuk-net

volumes:
  ktp_pgdata:
    name: ktp_pgdata
