version: "3.8"
services:
  api:
    build:
      context: ../backend
      dockerfile: ../ops/backend/Dockerfile
    env_file:
      - ./env.backend
    ports:
      - "5000:8080"
    working_dir: /app/Api
    depends_on: []

  cashier:
    build:
      context: ../frontend-cashier
      dockerfile: ../ops/frontend-cashier/Dockerfile
    env_file:
      - ./env.frontend-cashier
    ports:
      - "3000:3000"
    depends_on:
      - api

  dashboard:
    build:
      context: ../frontend-dashboard
      dockerfile: ../ops/frontend-dashboard/Dockerfile
    env_file:
      - ./env.frontend-dashboard
    ports:
      - "3001:3000"
    depends_on:
      - api

networks:
  default:
    name: kuyumculuk-net

